---
- name: Check if target node is running Windows
  ansible.builtin.assert:
    that: "ansible_os_family == 'Windows'"
    fail_msg: "{{ ansible_distribution }} is not supported for this role"
    quiet: true
