---

- name: Check for Windows service IIS
  ansible.builtin.win_service:
    name: w3svc
  register: iis

- name: Check for Windows service MSMQ
  ansible.builtin.win_service:
    name: msmq
  register: msmq

- name: Check for Windows service ADDC
  ansible.builtin.win_service:
    name: dns
  register: addc

- name: Check for Windows service MSSQL
  ansible.builtin.win_service:
    name: mssqlserver
  register: mssql

- name: Check for Windows service ADCS
  ansible.builtin.win_service:
    name: certsvc
  register: adcs

- name: Build host specific collectors based on service status
  ansible.builtin.set_fact:
    host_specific_collectors: "{{ [] +
      (['iis'] if iis.exists and iis.state == 'running' else []) +
      (['msmq'] if msmq.exists and msmq.state == 'running' else []) +
      (['ad'] if addc.exists and addc.state == 'running' else []) +
      (['adcs'] if adcs.exists and adcs.state == 'running' else []) +
      (['mssql'] if mssql.exists and mssql.state == 'running' else []) }}"

- name: Merge common collectors with host specific collectors identified
  ansible.builtin.set_fact:
    enabled_collectors: "{{ (windows_exporter_common_collectors + host_specific_collectors) | join(',') }}"

- name: Print windows exporter collectors to be enabled
  ansible.builtin.debug:
    msg:
    - "Host specific collector(s) identified: {{ host_specific_collectors | join(',') }}"
    - "Collectors to be enabled: {{ enabled_collectors }}"
