---
# tasks file for ansible-windows-exporter

- name: Include asserts
  ansible.builtin.include_tasks: 
    file: asserts.yml

- name: Include facts
  ansible.builtin.include_tasks: 
    file: facts.yml

- name: Include install
  ansible.builtin.include_tasks: 
    file: install.yml

